### ISSUE TITLE
build命令找不到

### ISSUE THREAD

**Issue by qiyeboy** [YinTianliang/NT4_CMD#1]
'build' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by Aloxaf** [comment]
确认在 Win10 上会出现这个问题

**Comment by Aloxaf** [comment]
> 确认在 Win10 上会出现这个问题

好像是个很严重的问题, 所有平台都无法构建,
我删掉了 NTOSBE 中不该删掉的部分, 然而因为玄学原因在之前的虚拟机上还是能够正常运行

将 NTOSBE 改用 submodule 引入后解决

Win10 x64 家庭版 测试通过, 请确认一下你那里能否正常构建

感谢指出这个问题!

**Comment by qiyeboy** [comment]
@Aloxaf 谢谢大佬，已经好使了，请问一下这个和现在win7/10上的功能差别大吗

**Comment by Aloxaf** [comment]
@qiyeboy 差别确实有, 不过主要影响写脚本
我没做过详细的测试, 但是已知的缺陷有
- 没有变量延迟扩展
- `for /f` 不支持 `usebackq` 参数
- `if` 的 `compare-op` 不支持小写
- `set` 没有 `/p` 开关

对日常脚本的兼容性估计还不如  [wine cmd](https://github.com/wine-mirror/wine/tree/master/programs/cmd)
不过除此之外对运用了奇技淫巧的脚本的兼容性应该比 wcmd 高

**Comment by qiyeboy** [comment]
@Aloxaf ReactOS cmd效果怎么样

**Comment by Aloxaf** [comment]
@qiyeboy 这个感觉不错, 完成度挺高的, 回头试试在 Win 上构建一下
目前只发现几个无伤大雅的 bug (基本上都是 undocumented 功能, 能不能算 bug 都不知道...

## 有些功能只在脚本模式下工作
```batch
setlocal enabledelayedexpansion
set a=123
echo !a!
rem expect: 123

set /p=hello<nul&&echo world
rem expect: helloworld
```

## 句柄备份
```batch
@echo off 2>nul 3>&2
bad_cmd
rem expect: no output
pause
```
## 一些 undocumented 环境变量
```batch
cmd /c exit /b 2
echo %=ExitCode% %=ExitCodeAscii%
rem expect: 00000041 A

echo %__APPDIR__%
rem expect: C:\Windows\system32
```
