### ISSUE TITLE
您好，我想请教一下，如果我想对其中的代码进行更改，我应该如何调试这个项目呢

### ISSUE THREAD

**Issue by Cc28256** [YinTianliang/NT4_CMD#2]
这个项目能编译成X64的吗？

**Comment by Aloxaf** [comment]
1. 将 start_build.bat 中的 SIZ_NTARCH 改为 amd64 也许可以编译成 x64 的，不过 NT4 本身不支持 x64，能不能成功编译、编译出来能不能成功运行还是个未知数
2. 将 SIZ_NTBLD 改为 chk 就能编译出带调试符号的版本，但我没有 Windows 下的调试经验，怎么调试咱就不知道了（也许要用 windgb 一类的

**Comment by Cc28256** [comment]
非常感谢您在百忙之中的回复，另外祝你在即将到来的端午快乐 ：）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月8日(星期二) 中午11:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Aloxaf/NT4_CMD] 您好，我想请教一下，如果我想对其中的代码进行更改，我应该如何调试这个项目呢 (#2)





  
将 start_build.bat 中的 SIZ_NTARCH 改为 amd64 也许可以编译成 x64 的，不过 NT4 本身不支持 x64，能不能成功编译、编译出来能不能成功运行还是个未知数
 
将 SIZ_NTBLD 改为 chk 就能编译出带调试符号的版本，但我没有 Windows 下的调试经验，怎么调试咱就不知道了（也许要用 windgb 一类的

**Comment by Aloxaf** [comment]
不客气，同预祝端午快乐
